# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "hide-payment-methods"
client_id = "581d5e17d9b9f69067aa6c609036621e"
application_url = "https://singer-trained-resume-math.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_payment_customizations,read_payment_customizations"

[auth]
redirect_urls = [
  "https://singer-trained-resume-math.trycloudflare.com/auth/callback",
  "https://singer-trained-resume-math.trycloudflare.com/auth/shopify/callback",
  "https://singer-trained-resume-math.trycloudflare.com/api/auth/callback",
  "https://singer-trained-resume-math.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "loch-test.myshopify.com"
